apiVersion: v1
kind: Service
metadata:
  name: backend
spec: 
  selector:
    # selector label in service is much older than deployment(it has been created recently)
    # that's why no matchLables
    app: second-app
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
  type: LoadBalancer

