apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: kuldeepkashyap/kube-network-task-api:latest
          env:
            - name: TASKS_FOLDER
              value: tasks
            - name: AUTH_ADDRESS
              # value: localhost
              value: "auth-service.default"
              # here first one service name and second one namespace(use to group resources) name